
import { DataItem, Category } from '@/types';

// Sample data since we're not connecting to a real API yet
export const SAMPLE_DATA: DataItem[] = [
  {
    id: '1',
    title: 'Managing Tomato Blight in Wet Seasons',
    description: 'Effective strategies for managing tomato blight during rainy seasons in Kenya',
    category: 'issues' as Category,
    date: '2023-11-15',
    source: 'Kenya Agricultural Research Institute',
    content: 'Tomato blight is a common disease that affects tomato crops during wet seasons. Symptoms include dark spots on leaves, stems, and fruits. To manage tomato blight: 1) Plant resistant varieties 2) Improve drainage in your field 3) Apply appropriate fungicides preventatively 4) Practice crop rotation 5) Remove and destroy infected plants to prevent spread.',
    tags: ['disease', 'tomatoes', 'wet season', 'fungal disease'],
    location: 'Central Kenya',
  },
  {
    id: '2',
    title: 'Tender: Supply of Agricultural Inputs to Nakuru County',
    description: 'Tender notice for the supply of agricultural inputs to Nakuru County',
    category: 'tender',
    date: '2023-12-01',
    source: 'Nakuru County Government',
    content: 'The Nakuru County Government invites sealed bids from eligible candidates for the supply of agricultural inputs including certified seeds, fertilizers, and pesticides. Interested bidders must provide documentation of previous similar contracts, tax compliance, and business registration.',
    tags: ['tender', 'agricultural inputs', 'Nakuru'],
    location: 'Nakuru County',
    deadline: '2023-12-31',
    contact: 'procurement@nakuru.go.ke',
    url: 'https://nakuru.go.ke/tenders'
  },
  {
    id: '3',
    title: 'Mobile Market Price Information System',
    description: 'A solution that provides real-time market prices to farmers via SMS',
    category: 'solutions',
    date: '2023-12-05',
    source: 'AgriTech Innovations',
    content: 'Our Mobile Market Price Information System allows farmers to receive daily price updates for different crops across multiple markets in Kenya. The system uses SMS to reach farmers without smartphones and works in areas with limited internet connectivity. Farmers simply send a text with their crop and location to receive current market prices, helping them make informed decisions about when and where to sell their produce.',
    tags: ['market access', 'price information', 'SMS', 'technology'],
    location: 'Nationwide',
  },
  {
    id: '4',
    title: 'Drought-Resistant Maize Varieties for Eastern Kenya',
    description: 'Information on drought-resistant maize varieties suitable for Eastern Kenya',
    category: 'solutions' as Category,
    date: '2023-10-20',
    source: 'Kenya Seed Company',
    content: 'Eastern Kenya often experiences drought conditions that affect maize production. Several drought-resistant varieties have been developed specifically for these conditions, including KDV-1, KDV-4, and Katumani. These varieties mature early (in about 90-120 days) and can produce reasonable yields even with limited rainfall. Proper spacing and timely planting are crucial for success with these varieties.',
    tags: ['drought', 'maize', 'Eastern Kenya', 'seed varieties'],
    location: 'Eastern Kenya',
  },
  {
    id: '5',
    title: 'Tender: Construction of Irrigation Infrastructure in Kitui',
    description: 'Tender for the construction of irrigation infrastructure in Kitui County',
    category: 'tender',
    date: '2023-11-25',
    source: 'Ministry of Agriculture',
    content: 'The Ministry of Agriculture invites tenders for the construction of irrigation infrastructure in Kitui County. The project involves construction of water intake structures, main canals, distribution networks, and farm inlets to serve approximately 2,000 hectares of farmland.',
    tags: ['irrigation', 'construction', 'infrastructure', 'Kitui'],
    location: 'Kitui County',
    deadline: '2024-01-15',
    contact: 'tenders@agriculture.go.ke',
    url: 'https://agriculture.go.ke/tenders'
  },
  {
    id: '6',
    title: 'Farm-to-Market Digital Marketplace',
    description: 'A digital platform connecting farmers directly to buyers, eliminating middlemen',
    category: 'solutions',
    date: '2023-12-10',
    source: 'Digital Farmers Network',
    content: 'Our Farm-to-Market Digital Marketplace is transforming how farmers sell their produce by connecting them directly with buyers. The platform allows farmers to list their produce with photos and details, while buyers can browse and purchase directly. The system includes secure payment processing, delivery coordination, and quality guarantees. By eliminating traditional middlemen, farmers receive better prices and buyers get fresher produce at competitive rates.',
    tags: ['market access', 'e-commerce', 'direct sales', 'middleman elimination'],
    location: 'Nairobi, Nakuru, Kiambu, Machakos',
  },
  {
    id: '7',
    title: 'Rural Produce Collection Points Network',
    description: 'A network of rural collection centers that aggregate and store produce for efficient transportation',
    category: 'solutions',
    date: '2024-01-05',
    source: 'AgriLogistics Kenya',
    content: 'Our Rural Produce Collection Points Network addresses one of the biggest challenges in agricultural supply chains - getting produce from remote farms to markets efficiently. We have established collection centers in strategic rural locations where farmers can bring their produce. Each center has basic quality checking equipment, weighing facilities, and temporary storage. This aggregation allows for efficient transportation in bulk to markets, reducing per-unit transport costs and ensuring produce arrives fresh and undamaged.',
    tags: ['logistics', 'rural infrastructure', 'aggregation', 'transportation'],
    location: 'Western Kenya and Rift Valley',
  }
];
