
import { MarketLinkage } from '@/types';

export const marketLinkages: MarketLinkage[] = [
  {
    id: "ml1",
    name: "Direct-to-Consumer Farmers Markets",
    title: "Direct-to-Consumer Farmers Markets",
    description: "Connect directly with consumers through organized farmers markets across major urban centers",
    date: "2023-12-10",
    location: "Nairobi, Mombasa, Kisumu, Nakuru",
    organizer: "Kenya Farmers Market Association",
    participants: 120,
    providerName: "Urban Markets Initiative",
    crops: ["Vegetables", "Fruits", "Poultry", "Dairy"],
    markets: ["Urban markets", "Weekend markets"],
    type: "horizontal",
    requirements: ["Quality produce", "Consistent supply", "Transportation"],
    benefits: ["Direct consumer feedback", "Better margins", "Brand building"],
    contactInfo: "info@kfma.co.ke | +254712345678",
    tags: ["direct-sales", "urban-markets", "fresh-produce"]
  },
  {
    id: "ml2",
    name: "Export Market Facilitation",
    title: "Export Market Facilitation",
    description: "Get your produce to international markets through our export facilitation program",
    date: "2024-01-15",
    location: "Nationwide",
    organizer: "Kenya Export Promotion Council",
    participants: 45,
    providerName: "Global Markets Access",
    crops: ["Coffee", "Tea", "Avocados", "Macadamia", "Cut flowers"],
    markets: ["European Union", "Middle East", "North America"],
    type: "vertical",
    requirements: ["Global GAP certification", "Export permits", "Minimum volumes"],
    benefits: ["Premium prices", "Long-term contracts", "Currency diversification"],
    contactInfo: "exports@kepc.co.ke | +254723456789",
    tags: ["exports", "international-markets", "certification"]
  },
  {
    id: "ml3",
    name: "Supermarket Supply Chain",
    title: "Supermarket Supply Chain",
    description: "Join our program to supply major supermarket chains across East Africa",
    date: "2024-02-01",
    location: "Nairobi, Kampala, Dar es Salaam",
    organizer: "Retail Suppliers Association",
    participants: 75,
    providerName: "Retail Connect",
    crops: ["Vegetables", "Fruits", "Cereals", "Processed foods"],
    markets: ["Supermarket chains", "Mini-markets", "Convenience stores"],
    type: "vertical",
    requirements: ["Consistent quality", "Barcoded packaging", "Delivery capacity"],
    benefits: ["Steady demand", "Bulk orders", "Regional exposure"],
    contactInfo: "suppliers@retailconnect.co.ke | +254734567890",
    tags: ["retail", "supermarkets", "supply-chain"]
  },
  {
    id: "ml4",
    name: "Cooperative Marketing",
    title: "Cooperative Marketing",
    description: "Join a cooperative to benefit from collective marketing and better bargaining power",
    date: "2024-03-10",
    location: "Various Counties",
    organizer: "National Cooperative Alliance",
    participants: 250,
    providerName: "Cooperative Solutions",
    crops: ["Coffee", "Tea", "Dairy", "Cereals", "Potatoes"],
    markets: ["Processors", "Exporters", "Wholesale"],
    type: "horizontal",
    requirements: ["Cooperative membership", "Quality standards adherence", "Regular participation"],
    benefits: ["Bargaining power", "Shared resources", "Knowledge exchange"],
    contactInfo: "join@coops.co.ke | +254745678901",
    tags: ["cooperative", "collective-marketing", "bargaining-power"]
  },
  {
    id: "ml5",
    name: "Hospitality Industry Supply",
    title: "Hospitality Industry Supply",
    description: "Supply hotels, restaurants, and catering companies with fresh farm produce",
    date: "2024-01-25",
    location: "Tourism Hubs",
    organizer: "Hospitality Procurement Network",
    participants: 60,
    providerName: "HoReCa Supply Chain",
    crops: ["Premium vegetables", "Fruits", "Herbs", "Poultry", "Meat"],
    markets: ["Hotels", "Restaurants", "Catering companies"],
    type: "vertical",
    requirements: ["Premium quality", "Delivery reliability", "Food safety standards"],
    benefits: ["Premium pricing", "Contracted supply", "Professional relationships"],
    contactInfo: "supply@horeca.co.ke | +254756789012",
    tags: ["hospitality", "hotels", "restaurants", "premium-produce"]
  },
  {
    id: "ml6",
    name: "Aggregation Centers",
    title: "Aggregation Centers",
    description: "Use our network of rural aggregation centers to consolidate produce for market",
    date: "2024-02-15",
    location: "Rural Counties",
    organizer: "Rural Market Access Initiative",
    participants: 350,
    providerName: "Aggregation Solutions",
    crops: ["Maize", "Beans", "Potatoes", "Sorghum", "Millet"],
    markets: ["Millers", "Wholesalers", "Government procurement"],
    type: "horizontal",
    requirements: ["Quality grading acceptance", "Minimum quantities", "Standard packaging"],
    benefits: ["Reduced transportation costs", "Better market access", "Quality control support"],
    contactInfo: "centers@aggregation.co.ke | +254767890123",
    tags: ["aggregation", "rural-markets", "logistics"]
  },
  {
    id: "ml7",
    name: "Digital Marketplace Platform",
    title: "Digital Marketplace Platform",
    description: "List your produce on our digital platform connecting farmers directly with buyers",
    date: "2024-03-01",
    location: "Online - Nationwide",
    organizer: "AgriTech Innovations",
    participants: 500,
    providerName: "Digital Farmers Market",
    crops: ["All crop categories", "Livestock", "Dairy", "Poultry"],
    markets: ["Wholesalers", "Retailers", "Processors", "Consumers"],
    type: "horizontal",
    requirements: ["Smartphone/internet access", "Quality photos", "Accurate descriptions"],
    benefits: ["Wide market reach", "Direct negotiations", "Price transparency"],
    contactInfo: "support@digitalfarm.co.ke | +254778901234",
    tags: ["digital", "e-commerce", "direct-sales", "technology"]
  },
  {
    id: "ml8",
    name: "Contract Growing Scheme",
    title: "Contract Growing Scheme",
    description: "Secure contracts with processors and exporters before planting season",
    date: "2024-04-01",
    location: "Major Agricultural Regions",
    organizer: "Contract Farming Network",
    participants: 200,
    providerName: "Harvest Assured",
    crops: ["French beans", "Baby corn", "Chillies", "Groundnuts", "Soybeans"],
    markets: ["Food processors", "Exporters", "Oil producers"],
    type: "vertical",
    requirements: ["Land ownership/lease", "Irrigation access", "Training completion"],
    benefits: ["Guaranteed market", "Input financing", "Technical support"],
    contactInfo: "contracts@harvestassured.co.ke | +254789012345",
    tags: ["contract-farming", "guaranteed-market", "export-crops"]
  }
];
