import { TrainingEvent } from '@/types';

export const mockTrainingEvents: TrainingEvent[] = [
  {
    id: "1",
    title: "Advanced Tomato Growing Techniques",
    description: "Learn the latest techniques for growing high-quality tomatoes, including disease prevention, optimal fertilization, and harvest timing. This hands-on workshop will cover greenhouse and open field production systems.",
    providerId: "provider1",
    providerName: "Kilimo Extension Services",
    date: "2023-08-15T09:00:00Z",
    location: "Agricultural Training Center, Thika",
    topics: ["tomato production", "disease management", "greenhouse farming"],
    capacity: 50,
    registeredCount: 35,
    cost: 0,
    attendees: 35,
    tags: ["tomato", "greenhouse", "fertilizer"],
    trainer: "Dr. John Kimani"
  },
  {
    id: "2",
    title: "Quality Control for Fresh Produce Exporters",
    description: "This comprehensive training covers all aspects of quality control for fresh produce export, including EU regulations, documentation requirements, sampling techniques, and audit preparation.",
    providerId: "provider2",
    providerName: "Export Quality Services",
    date: "2023-08-28T10:00:00Z",
    location: "Sarova Panafric Hotel, Nairobi",
    topics: ["export standards", "quality control", "certification", "EU regulations"],
    capacity: 30,
    registeredCount: 28,
    cost: 5000,
    attendees: 28,
    tags: ["export", "quality", "certification", "EU"],
    trainer: "Ms. Jane Ochieng"
  },
  {
    id: "3",
    title: "Organic Certification Workshop",
    description: "Step-by-step guidance on the organic certification process for small and medium-scale farmers. Learn about record-keeping requirements, approved inputs, conversion periods, and marketing strategies.",
    providerId: "provider3",
    providerName: "Kenya Organic Agriculture Network",
    date: "2023-09-05T09:30:00Z",
    location: "Kisumu Agricultural Society Showground",
    topics: ["organic certification", "record keeping", "organic inputs"],
    capacity: 40,
    registeredCount: 22,
    cost: 2500,
    attendees: 22,
    tags: ["organic", "record", "inputs"],
    trainer: "Mr. David Mwangi"
  },
  {
    id: "4",
    title: "Pesticide Safety and Application",
    description: "Learn safe and effective pesticide application techniques, including proper handling, calibration of equipment, environmental protection measures, and health safety protocols.",
    providerId: "provider4",
    providerName: "Agrochemical Association of Kenya",
    date: "2023-09-12T08:00:00Z",
    location: "Machakos Farmers Training Center",
    topics: ["pesticide safety", "application techniques", "equipment calibration"],
    capacity: 60,
    registeredCount: 45,
    cost: 0,
    attendees: 45,
    tags: ["pesticide", "application", "calibration"],
    trainer: "Dr. Emily Mwangi"
  },
  {
    id: "5",
    title: "Post-Harvest Management for Fruits and Vegetables",
    description: "Reduce post-harvest losses through improved handling, storage, and transportation techniques. This training covers cold chain management, packaging solutions, and value addition opportunities.",
    providerId: "provider5",
    providerName: "Horticultural Crops Directorate",
    date: "2023-09-20T10:00:00Z",
    location: "KALRO Center, Meru",
    topics: ["post-harvest management", "cold chain", "value addition"],
    capacity: 35,
    registeredCount: 18,
    cost: 1000,
    attendees: 18,
    tags: ["post-harvest", "cold", "value"],
    trainer: "Ms. Mary Wanjiru"
  },
  {
    id: "6",
    title: "Food Safety Management Systems (HACCP)",
    description: "Comprehensive training on implementing HACCP principles in agricultural production and handling. Learn to identify critical control points and develop monitoring systems for ensuring food safety.",
    providerId: "provider6",
    providerName: "Kenya Bureau of Standards",
    date: "2023-10-03T09:00:00Z",
    location: "KEBS Headquarters, Nairobi",
    topics: ["HACCP", "food safety", "critical control points"],
    capacity: 25,
    registeredCount: 25,
    cost: 8000,
    attendees: 25,
    tags: ["HACCP", "food", "control"],
    trainer: "Dr. John Kimani"
  },
  {
    id: "7",
    title: "Digital Tools for Farm Record Keeping",
    description: "Introduction to smartphone applications and digital tools for maintaining farm records, tracking inputs and harvests, and preparing for certification audits.",
    providerId: "provider7",
    providerName: "Digital Farmers Kenya",
    date: "2023-10-10T14:00:00Z",
    location: "Virtual (Zoom)",
    topics: ["digital agriculture", "record keeping", "farm management"],
    capacity: 100,
    registeredCount: 67,
    cost: 500,
    attendees: 67,
    tags: ["digital", "record", "management"],
    trainer: "Ms. Jane Ochieng"
  },
  {
    id: "8",
    title: "Soil Testing and Fertility Management",
    description: "Learn to interpret soil test results and develop effective fertility management strategies. This training covers sampling techniques, understanding lab reports, and creating fertilizer plans.",
    providerId: "provider8",
    providerName: "Soil Health Initiative",
    date: "2023-10-18T09:00:00Z",
    location: "ATC Eldoret",
    topics: ["soil health", "soil testing", "fertility management"],
    capacity: 45,
    registeredCount: 32,
    cost: 1500,
    attendees: 32,
    tags: ["soil", "testing", "fertility"],
    trainer: "Mr. David Mwangi"
  },
  {
    id: "9",
    title: "Quality Assurance for Dairy Production",
    description: "Comprehensive training on quality assurance in milk production, handling, and processing. Learn about hygiene requirements, testing protocols, and quality standards.",
    providerId: "provider9",
    providerName: "Kenya Dairy Board",
    date: "2023-10-25T09:00:00Z",
    location: "Nakuru Agricultural Showground",
    topics: ["dairy", "milk quality", "hygiene", "testing"],
    capacity: 50,
    registeredCount: 28,
    cost: 2000,
    attendees: 28,
    tags: ["dairy", "quality", "hygiene", "testing"],
    trainer: "Ms. Mary Wanjiru"
  }
];
