// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

const SUPABASE_URL = 'https://xgtmpfginlxrntixpqim.supabase.co';
const SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhndG1wZmdpbmx4cm50aXhwcWltIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0NzYzNDMsImV4cCI6MjA3MDA1MjM0M30.UityH607C-tazH7bvhS5G5CJaO2u7OhjIkoFQ6kPF10';

export const supabase = createClient(SUPABASE_URL, SUPABASE_ANON_KEY);
